name = "spec"
version = "0.1.0"
defaultTargets = ["Spec"]

[[lean_lib]]
name = "Spec"
glob = "Spec.+"

# [[require]]
# name = "batteries"
# scope = "leanprover-community"
# rev = "main"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "Colorized"
scope = "algebraic-dev"

[[require]]
name = "Pipes"
path = "../lean-pipes"
# scope = "srhhma"
# git = "https://github.com/srhhma/lean-pipes"

[[require]]
name = "aesop"
scope = "leanprover-community"
rev = "master"
